uint8 audio_control_type
uint8 audio_control_level
uint8 corning_led_type
uint8 three_color_led_type
int32 atomic_action_type
float32 atomic_action_value
float32 clamp_left_motor_value
float32 clamp_right_motor_value

# enum class AudioControlType : uint32_t {
#   NONE = 0,
#   BUMP_FAULT = 1,
#   FORWARD = 2,
#   BACKWARD = 3,
#   OBSTACLE_WARN = 4,
#   OBSTACLE_STOP = 5,
#   LOW_BATTERY = 6
# } 

# audio_control_level  0 ~ 30 