uint8 three_color_led_type
uint8 corning_led_type

# 三色灯控制类型
# enum class ThreeColorLedType : uint32_t {
#     GREEN_ON                 = 0x00000100,
#     YELLOW_ON                = 0x00000010,
#     RED_ON                   = 0x00000001,
    
#     YELLOW_GREEN_ON          = 0x00000110,
#     RED_YELLOW_ON            = 0x00000011,
#     RED_GREEN_ON             = 0x00000101,
#     RED_YELLOW_GREEN_ON      = 0x00000111,
    
#     RED_TWINKLE              = 0x10000001,
#     YELLOW_TWINKLE           = 0x10000010,
#     GREEN_TWINKLE            = 0x10000100,
    
#     YELLOW_GREEN_TWINKLE     = 0x10000110,
#     RED_YELLOW_TWINKLE       = 0x10000011,
#     RED_GREEN_TWINKLE        = 0x10000101,
#     RED_YELLOW_GREEN_TWINKLE = 0x10000111,
    
#     YELLOW_GREEN_SWITCH      = 0x20000110,
#     RED_YELLOW_SWITCH        = 0x20000011,
#     RED_GREEN_SWITCH         = 0x20000101,
    
#     LIGHT_ALL_ON             = 0x00000111,
#     LIGHT_OFF                = 0x00000000,
# }