int32 sensor_id

std_msgs/String status
#absent
#ok
#error

float64 value


#    { key: "emergencyStops", name: "急停开关", topic: "/ros/emergencyStops" },
#    { key: "encoder", name: "拉线编码器", topic: "/ros/wireEncoder" },
#    { key: "imus", name: "IMU", topic: "/ros/imus" },
#    { key: "inPositionSwitches", name: "到位开关", topic: "/ros/inPositionSwitches" },
#    { key: "navigationRadars", name: "导航雷达", topic: "/ros/navigationRadars" },
#    { key: "safeLasers", name: "安全激光", topic: "/ros/safeLasers" }

